x=int(input("Enter first number"))
y=int(input("Enter second number"))
print("addition of two numbers is")
print(x+y)
print("Subtraction of two numbers is")
print(x-y)
print("multiplication of two numbers is")
print(x*y)
if y!=0:
    print("division of two numbers is")
    print(x/y)
else:print("division is not possible")
print("Exponont of x to y is")
print(pow(x,y))
		
